from notation import *

def levels_up(c):
    scramble_empty = scrambles['empty']

    # yellow_cross
    c.load(templates['yellow_cross'], scramble_empty)
    c.image('yc_up')

    # second_level
    c.load(templates['second_level'], scramble_empty)
    c.image('sl_up')

    # first_level
    c.load(templates['first_level'], scramble_empty)
    c.image('fl_up')

    # white_cross
    c.load(templates['white_cross'], scramble_empty)
    c.image('wc_up')

def levels_down(c):
    template_neutral = templates['neutral']
    scramble_empty = scrambles['empty']
    scramble_x2 = "L2 R2 M' M'"

    # yellow_cross
    c.load(templates['yellow_cross'], scramble_empty)
    c.execute(scramble_x2, display=False)
    c.load(template_neutral, scramble_empty)
    c.image('yc_down')

    # second_level
    c.execute(scramble_x2, display=False)
    c.load(templates['second_level'], scramble_empty)
    c.execute(scramble_x2, display=False)
    c.load(template_neutral, scramble_empty)
    c.image('sl_down')

    # first_level
    c.execute(scramble_x2, display=False)
    c.load(templates['first_level'], scramble_empty)
    c.execute(scramble_x2, display=False)
    c.load(template_neutral, scramble_empty)
    c.image('fl_down')

    # white_cross
    c.execute(scramble_x2, display=False)
    c.load(templates['white_cross'], scramble_empty)
    c.execute(scramble_x2, display=False)
    c.load(template_neutral, scramble_empty)
    c.image('wc_down')

def white_cross(c):
    template_neutral = templates['neutral']
    scramble_empty = scrambles['empty']
    scramble_x2 = "L2 R2 M' M'"

    # base
    c.load(templates['white_cross'], scramble_empty)
    c.execute(scramble_x2, display=False)
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('wc_case_1_0')

    # white_cross case_0
    c.execute("R2 U", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('wc_case_0')
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('wc_case_0_0')
    c.load(template_neutral, scrambles['neutral_u_'])
    c.image('wc_case_0_a')
    c.execute("U'", display=False)

    # white_cross case_1
    # c.execute("R2", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('wc_case_1')
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('wc_case_1_0')
    c.load(template_neutral, scrambles['neutral_r_'])
    c.image('wc_case_1_a')
    c.execute("R2", display=False)

    # white_cross case_2
    c.execute("F R F' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('wc_case_2')
    c.load(templates['neutral'], scrambles['neutral_u'])
    c.image('wc_case_2_a')
    c.execute("U", display=False)
    c.load(templates['neutral'], scrambles['neutral_f'])
    c.image('wc_case_2_b')
    c.execute("F", display=False)
    c.load(templates['neutral'], scrambles['neutral_r_'])
    c.image('wc_case_2_c')
    c.execute("R'", display=False)
    c.load(templates['neutral'], scrambles['neutral_f_'])
    c.image('wc_case_2_d')

    # white_cross case_3
    c.execute("F' F R F' U' R2", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('wc_case_3')
    c.load(templates['neutral'], scrambles['neutral_r'])
    c.image('wc_case_3_a')
    c.execute("R", display=False)
    c.load(templates['neutral'], scrambles['neutral_f_'])
    c.image('wc_case_3_b')
    c.execute("F'", display=False)
    c.load(templates['neutral'], scrambles['neutral_u_'])
    c.image('wc_case_3_c')
    c.execute("U'", display=False)
    c.load(templates['neutral'], scrambles['neutral_f'])
    c.image('wc_case_3_d')
    c.execute("F", display=False)

    # white_cross case_4
    c.execute("R2 F' R U R' F", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('wc_case_4')
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('wc_case_4_0')
    c.load(template_neutral, scrambles['neutral_r'])
    c.image('wc_case_4_a')
    # c.load(template_neutral, scramble_empty)
    # c.image('wc_case_4_0_a')
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('wc_case_4_0a')
    c.execute("R", display=False)
    c.load(template_neutral, scrambles['neutral_u'])
    c.image('wc_case_4_b')
    # c.load(template_neutral, scramble_empty)
    # c.image('wc_case_4_0_b')
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('wc_case_4_0b')
    c.execute("U", display=False)
    c.load(template_neutral, scrambles['neutral_r_'])
    c.image('wc_case_4_c')
    # c.load(template_neutral, scramble_empty)
    # c.image('wc_case_4_0_c')
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('wc_case_4_0c')
    c.execute("R'", display=False)
    c.load(template_neutral, scrambles['neutral_f'])
    c.image('wc_case_4_d')
    c.load(template_neutral, scramble_empty)
    # c.image('wc_case_4_0_d')
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('wc_case_4_0d')
    c.execute("F2", display=False)
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('wc_down_0')

def first_level(c):
    template_neutral = templates['neutral']
    scramble_empty = scrambles['empty']
    scramble_x2 = "L2 R2 M' M'"

    # base
    c.load(templates['first_level'], scramble_empty)
    c.execute(scramble_x2, display=False)

    # first_level case_1
    c.execute("F' U F", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('fl_case_1')
    c.load(templates['neutral'], scrambles['neutral_f_'])
    c.image('fl_case_1_a')
    c.execute("F'", display=False)
    c.load(templates['neutral'], scrambles['neutral_u_'])
    c.image('fl_case_1_b')
    c.execute("U'", display=False)
    c.load(templates['neutral'], scrambles['neutral_f'])
    c.image('fl_case_1_c')
    c.execute("F", display=False)

    # first_level case_2
    c.execute("R U' R'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('fl_case_2')
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('fl_case_2_0')
    c.load(templates['neutral'], scrambles['neutral_r'])
    c.image('fl_case_2_a')
    c.execute("R", display=False)
    c.load(templates['neutral'], scrambles['neutral_u'])
    c.image('fl_case_2_b')
    c.execute("U", display=False)
    c.load(templates['neutral'], scrambles['neutral_r_'])
    c.image('fl_case_2_c')
    c.execute("R'", display=False)
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('fl_down_0')

    # first_level case_3
    c.execute("R U' R' F' U' U' F U", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('fl_case_3')
    c.load(templates['neutral'], scrambles['neutral_r'])
    c.image('fl_case_3_a')
    c.execute("R", display=False)
    c.load(templates['neutral'], scrambles['neutral_u'])
    c.image('fl_case_3_b')
    c.execute("U", display=False)
    c.load(templates['neutral'], scrambles['neutral_u'])
    c.image('fl_case_3_c')
    c.execute("U", display=False)
    c.load(templates['neutral'], scrambles['neutral_r_'])
    c.image('fl_case_3_d')
    c.execute("R'", display=False)
    c.load(templates['neutral'], scrambles['neutral_u_'])
    c.image('fl_case_3_e')

    # first_level case_4
    c.execute("R U' R'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('fl_case_4')
    c.load(templates['neutral'], scrambles['neutral_r'])
    c.image('fl_case_4_a')
    c.execute("R", display=False)
    c.load(templates['neutral'], scrambles['neutral_u'])
    c.image('fl_case_4_b')
    c.execute("U", display=False)
    c.load(templates['neutral'], scrambles['neutral_r_'])
    c.image('fl_case_4_c')
    c.execute("R'", display=False)
    c.load(templates['neutral'], scrambles['neutral_u_'])
    c.image('fl_case_4_d')
    c.execute("U'", display=False)
    c.load(templates['neutral'], scramble_empty)
    c.image('fl_case_4_e')

def second_level(c):
    template_neutral = templates['neutral']
    scramble_empty = scrambles['empty']
    scramble_x2 = "L2 R2 M' M'"

    # base
    c.load(templates['second_level'], scramble_empty)
    c.execute(scramble_x2, display=False)

    # second_level case_1
    c.execute("F' U' F U R U R' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('sl_case_1')
    c.load(templates['neutral'], scrambles['neutral_u'])
    c.image('sl_case_1_a')
    c.execute("U", display=False)
    c.load(templates['neutral'], scrambles['neutral_r'])
    c.image('sl_case_1_b')
    c.execute("R", display=False)
    c.load(templates['neutral'], scrambles['neutral_u_'])
    c.image('sl_case_1_c')
    c.execute("U'", display=False)
    c.load(templates['neutral'], scrambles['neutral_r_'])
    c.image('sl_case_1_d')
    c.execute("R'", display=False)
    c.load(templates['neutral'], scrambles['neutral_u_'])
    c.image('sl_case_1_e')
    c.execute("U'", display=False)
    c.load(templates['neutral'], scrambles['neutral_f_'])
    c.image('sl_case_1_f')
    c.execute("F'", display=False)
    c.load(templates['neutral'], scrambles['neutral_u'])
    c.image('sl_case_1_g')
    c.execute("U", display=False)
    c.load(templates['neutral'], scrambles['neutral_f'])
    c.image('sl_case_1_h')
    c.execute("F", display=False)

    # second_level case_2
    c.execute("F U F' U' L' U' L U", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('sl_case_2')
    c.load(templates['neutral'], scrambles['neutral_u_'])
    c.image('sl_case_2_a')
    c.execute("U'", display=False)
    c.load(templates['neutral'], scrambles['neutral_l_'])
    c.image('sl_case_2_b')
    c.execute("L'", display=False)
    c.load(templates['neutral'], scrambles['neutral_u'])
    c.image('sl_case_2_c')
    c.execute("U", display=False)
    c.load(templates['neutral'], scrambles['neutral_l'])
    c.image('sl_case_2_d')
    c.execute("L", display=False)
    c.load(templates['neutral'], scrambles['neutral_u'])
    c.image('sl_case_2_e')
    c.execute("U", display=False)
    c.load(templates['neutral'], scrambles['neutral_f'])
    c.image('sl_case_2_f')
    c.execute("F", display=False)
    c.load(templates['neutral'], scrambles['neutral_u_'])
    c.image('sl_case_2_g')
    c.execute("U'", display=False)
    c.load(templates['neutral'], scrambles['neutral_f_'])
    c.image('sl_case_2_h')
    c.execute("F'", display=False)
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('sl_down_0')

def yellow_cross(c):
    template_neutral = templates['neutral']
    scramble_empty = scrambles['empty']
    scramble_x2 = "L2 R2 M' M'"

    # base
    c.load(templates['yellow_cross'], scramble_empty)
    c.execute("R U R' U' R U R' U' D'", display=False)
    c.execute("R U R' U' R U R' U' D'", display=False)
    c.execute("R U R' U' R U R' U' D' D'", display=False)
    c.execute(scramble_x2, display=False)
    c.execute("U' L' U R U' L U R'", display=False)
    c.execute("U' L' U R U' L U R'", display=False)
    c.execute("R U2 R' U' R U' R'", display=False)
    c.execute("R U2 R' U' R U' R'", display=False)
    c.execute("F U R U' R' F'", display=False)
    c.execute("F U R U' R' F'", display=False)

    # yellow_cross case_2
    c.load(template_neutral, scramble_empty)
    c.image('yc_case_2')
    c.load(template_neutral, scrambles['neutral_f'])
    c.image('yc_case_2_a')
    c.execute("F", display=False)
    c.load(template_neutral, scrambles['neutral_r'])
    c.image('yc_case_2_b')
    c.execute("R", display=False)
    c.load(template_neutral, scrambles['neutral_u'])
    c.image('yc_case_2_c')
    c.execute("U", display=False)
    c.load(template_neutral, scrambles['neutral_r_'])
    c.image('yc_case_2_d')
    c.execute("R'", display=False)
    c.load(template_neutral, scrambles['neutral_u_'])
    c.image('yc_case_2_e')
    c.execute("U'", display=False)
    c.load(template_neutral, scrambles['neutral_f_'])
    c.image('yc_case_2_f')
    c.execute("F'", display=False)

    # yellow_cross case_3
    c.load(template_neutral, scramble_empty)
    c.image('yc_case_3')
    c.load(template_neutral, scrambles['neutral_f'])
    c.image('yc_case_3_a')
    c.execute("F", display=False)
    c.load(template_neutral, scrambles['neutral_r'])
    c.image('yc_case_3_b')
    c.execute("R", display=False)
    c.load(template_neutral, scrambles['neutral_u'])
    c.image('yc_case_3_c')
    c.execute("U", display=False)
    c.load(template_neutral, scrambles['neutral_r_'])
    c.image('yc_case_3_d')
    c.execute("R'", display=False)
    c.load(template_neutral, scrambles['neutral_u_'])
    c.image('yc_case_3_e')
    c.execute("U'", display=False)
    c.load(template_neutral, scrambles['neutral_f_'])
    c.image('yc_case_3_f')
    c.execute("F'", display=False)

    # yellow_cross case_4
    c.load(template_neutral, scramble_empty)
    c.image('yc_case_4')
    c.load(template_neutral, scrambles['neutral_y'])
    c.image('yc_case_4_a')
    c.execute("U D' E'", display=False)
    c.load(template_neutral, scrambles['neutral_y_'])
    c.image('yc_case_4_b')
    c.execute("U' D E", display=False)
    c.load(template_neutral, scrambles['neutral_r'])
    c.image('yc_case_4_c')
    c.execute("R", display=False)
    c.load(template_neutral, scrambles['neutral_u'])
    c.image('yc_case_4_d')
    c.execute("U", display=False)
    c.load(template_neutral, scrambles['neutral_r_'])
    c.image('yc_case_4_e')
    c.execute("R'", display=False)
    c.load(template_neutral, scrambles['neutral_u'])
    c.image('yc_case_4_f')
    c.execute("U", display=False)
    c.load(template_neutral, scrambles['neutral_r'])
    c.image('yc_case_4_g')
    c.execute("R", display=False)
    c.load(template_neutral, scrambles['neutral_u'])
    c.image('yc_case_4_h')
    c.execute("U", display=False)
    c.load(template_neutral, scrambles['neutral_u'])
    c.image('yc_case_4_i')
    c.execute("U", display=False)
    c.load(template_neutral, scrambles['neutral_r_'])
    c.image('yc_case_4_j')
    c.execute("R'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('yc_case_4_k')
    c.execute("R U R' U R U2 R'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('yc_case_4_l')
    c.load(template_neutral, scrambles['neutral_y'])
    c.image('yc_case_4_m')
    # c.execute("F' B S'", display=False)
    # c.load(template_neutral, scramble_empty)
    # c.image('yl_down_0')
    c.execute("U D' E'", display=False)

    # yellow_cross case_5
    c.load(template_neutral, scramble_empty)
    c.image('yc_case_5')

def third_level(c):
    template_neutral = templates['neutral']
    scramble_empty = scrambles['empty']
    scramble_x2 = "L2 R2 M' M'"

    # base
    c = Icube() #TODO: why is it necessary? - start
    c.execute(scramble_empty, display=False, reset=True) #TODO: why is it necessary? - end
    c.execute("R U R' U' R U R' U' D'", display=False)
    c.execute("R U R' U' R U R' U' D'", display=False)
    c.execute("R U R' U' R U R' U' D' D'", display=False)
    c.execute(scramble_x2, display=False)
    c.execute("U' L' U R U' L U R'", display=False)
    c.execute("U' L' U R U' L U R'", display=False)

    # third_level case_1
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_1')
    c.load(template_neutral, scrambles['neutral_r'])
    c.image('tl_case_1_a')
    c.execute("R", display=False)
    c.load(template_neutral, scrambles['neutral_u_'])
    c.image('tl_case_1_b')
    c.execute("U'", display=False)
    c.load(template_neutral, scrambles['neutral_l_'])
    c.image('tl_case_1_c')
    c.execute("L'", display=False)
    c.load(template_neutral, scrambles['neutral_u'])
    c.image('tl_case_1_d')
    c.execute("U", display=False)
    c.load(template_neutral, scrambles['neutral_r_'])
    c.image('tl_case_1_e')
    c.execute("R'", display=False)
    c.load(template_neutral, scrambles['neutral_u_'])
    c.image('tl_case_1_f')
    c.execute("U'", display=False)
    c.load(template_neutral, scrambles['neutral_l'])
    c.image('tl_case_1_g')
    c.execute("L", display=False)
    c.load(template_neutral, scrambles['neutral_u'])
    c.image('tl_case_1_h')
    c.execute("U", display=False)

    # third_level case_2
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_2')
    c.execute("R U' L' U R' U' L U", display=False)

    # third_level case_3
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_3')
    c.load(template_neutral, scrambles['neutral_x_'])
    c.image('tl_case_3_a')
    c.execute("L R' M'", display=False)
    c.load(template_neutral, scrambles['neutral_x_'])
    c.image('tl_case_3_b')
    c.execute("L R' M'", display=False)

    # third_level case_4
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4')
    c.load(template_neutral, scrambles['neutral_r'])
    c.image('tl_case_4_a')
    c.execute("R", display=False)
    c.load(template_neutral, scrambles['neutral_u'])
    c.image('tl_case_4_b')
    c.execute("U", display=False)
    c.load(template_neutral, scrambles['neutral_r_'])
    c.image('tl_case_4_c')
    c.execute("R'", display=False)
    c.load(template_neutral, scrambles['neutral_u_'])
    c.image('tl_case_4_d')
    c.execute("U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_e')
    c.execute("R U R' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_f')
    c.execute("R U R' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_g')
    c.execute("R U R' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_h')
    c.load(template_neutral, scrambles['neutral_d_'])
    c.image('tl_case_4_i')
    c.execute("D'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_j')
    c.execute("R U R' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_k')
    c.execute("R U R' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_l')
    c.execute("R U R' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_m')
    c.execute("R U R' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_n')
    c.load(template_neutral, scrambles['neutral_d_'])
    c.image('tl_case_4_o')
    c.execute("D'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_p')
    c.execute("R U R' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_q')
    c.execute("R U R' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_r')
    c.execute("R U R' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_s')
    c.execute("R U R' U'", display=False)
    c.load(template_neutral, scramble_empty)
    c.image('tl_case_4_t')
    c.load(template_neutral, scrambles['neutral_d_'])
    c.image('tl_case_4_u')
    c.execute("D'", display=False)
    c.load(template_neutral, scrambles['neutral_d_'])
    c.image('tl_case_4_v')
    c.execute("D'", display=False)

if __name__ == '__main__':
    # cube colourful
    c = Icube()
    c.execute(scrambles['empty'], display=False, reset=True)

    # steps
    levels_up(c)
    levels_down(c)

    # moves
    white_cross(c)
    first_level(c)
    second_level(c)
    yellow_cross(c)
    third_level(c)
